spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: vp93591@gmail.com
    password: gtks huzi lvnq srrn
    protocol: smtp
    properties:
      mail:
        smtp:
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeou: 5000
    thymeleaf:
      enable: true

envio:
  email:
    remetente: vp93591@gmail.com
    nomeRemetente: 'VitroX'

server:
  port: 8082