spring:
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
    thymeleaf:
      enable: true

envio:
  email:
    remetente: ${MAIL_FROM}
    nomeRemetente: ${MAIL_SENDER_NAME:VitroX}

server:
  port: ${SERVER_PORT:8082}